# Generated by Django 3.0.5 on 2021-01-10 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('maxcapacity', models.IntegerField()),
                ('vacancy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True, verbose_name='Booking Date')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Booking Time')),
                ('status', models.CharField(default='available', max_length=200)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='jobs.Hall')),
            ],
        ),
    ]
