# Generated by Django 3.0.5 on 2021-01-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
