# Generated by Django 3.0.5 on 2021-01-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210110_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='mems',
            field=models.IntegerField(default=0),
        ),
    ]
