# Generated by Django 3.0.5 on 2021-01-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Img',
        ),
    ]
