# Generated by Django 3.0.5 on 2021-01-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_film'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
